name: Wild Man Studio
favicon: null
layout_spectrum: 0.42404982866719365
typography_spectrum: 0.5608852303121239
title: Wild Man Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2c27'
    - '#61452f'
    - '#dfba90'
    - '#f0d5ce'
    - '#a38762'
  brandStrength: 0.5
  lightness: 0.5308161647990346
  saturation: 0.25
  rhythmicContrast: 0.9652288225479424
purpose: []
