name: Wild Man Studio
favicon: null
layout_spectrum: 0.98498
typography_spectrum: 0.66106
title: Wild Man Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2c27'
    - '#61452f'
    - '#dfba90'
    - '#f0d5ce'
    - '#a38762'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
